# Generated by Django 2.2.19 on 2023-04-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Название книги', verbose_name='Название книги')),
                ('text', models.TextField(help_text='Описание книги', verbose_name='Описание книги')),
                ('author', models.TextField(help_text='Автор книги', verbose_name='Автор книги')),
                ('pub_house', models.TextField(help_text='Издательство', verbose_name='Издательство')),
                ('pub_year', models.TextField(help_text='Год издания', verbose_name='Год издания')),
                ('book_add_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления книги')),
            ],
            options={
                'ordering': ['-book_add_date'],
            },
        ),
    ]
