# Generated by Django 2.2.19 on 2023-04-19 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_genre', models.TextField(help_text='Жанр книги', verbose_name='Жанр книги')),
                ('sub_genre', models.TextField(help_text='Поджанр книги', verbose_name='Поджанр книги')),
            ],
            options={
                'verbose_name': 'Жанры',
                'verbose_name_plural': 'Жанры',
                'ordering': ['main_genre'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Название книги', verbose_name='Название книги')),
                ('text', models.TextField(help_text='Описание книги', verbose_name='Описание книги')),
                ('author', models.TextField(help_text='Автор книги', verbose_name='Автор книги')),
                ('pub_house', models.TextField(help_text='Издательство', verbose_name='Издательство')),
                ('pub_year', models.DateTimeField(help_text='Год издания', verbose_name='Год издания')),
                ('image', models.ImageField(blank=True, upload_to='books/', verbose_name='Картинка')),
                ('book_add_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления книги')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='books.Genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Книги',
                'verbose_name_plural': 'Книги',
                'ordering': ['-book_add_date'],
            },
        ),
    ]
