# Generated by Django 2.2.19 on 2023-06-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='main_genre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='sub_genre',
        ),
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Поджанр книги', verbose_name='Поджанр книги')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_genres', to='books.Genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Поджанр',
                'verbose_name_plural': 'Поджанры',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='sub_genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_genres', to='books.SubGenre', verbose_name='Жанр'),
            preserve_default=False,
        ),
    ]
