# Generated by Django 2.2.19 on 2023-04-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-book_add_date'], 'verbose_name': 'Книги'},
        ),
    ]
