# Generated by Django 2.2.19 on 2023-04-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20230418_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.TextField(default=1, help_text='Жанр книги', verbose_name='Жанр книги'),
            preserve_default=False,
        ),
    ]
