# Generated by Django 2.2.19 on 2023-06-06 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20230605_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sub_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.SubGenre', verbose_name='Поджанр'),
        ),
    ]
