# Generated by Django 2.2.19 on 2024-04-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20240402_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='sub_genre',
            new_name='subgenre',
        ),
        migrations.AlterField(
            model_name='subgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgenres', to='books.Genre', verbose_name='Жанр'),
        ),
    ]
