# Generated by Django 2.2.19 on 2024-04-02 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20240402_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.PositiveIntegerField(help_text='Год издания', validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)], verbose_name='Год издания'),
        ),
    ]
